use_frameworks!

platform :ios, '8.0'

target 'CocopodsTest_Example' do
  pod 'CocopodsTest', :path => '../'

  target 'CocopodsTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
